#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import ts from "typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const version = "2.0.25";
const sources = ["LAWS.bend", "PROOF.bend", "proofs/kernel.bend", "proofs/abi.json", "proofs/types.d.ts", "scripts/verified-kernels.mjs"];
const output = "src/verified/generated/kernel.js";
const declarations = "src/verified/generated/kernel.d.ts";
const receipt = "src/verified/generated/manifest.json";
const read = (path) => readFileSync(resolve(root, path), "utf8");
const hash = (text) => createHash("sha256").update(text).digest("hex");
const inputs = () => Object.fromEntries(sources.map((path) => [path, hash(read(path))]));
const args = process.argv.slice(2);
if (args.length !== 1 || !["--write", "--check", "--artifact"].includes(args[0])) {
  throw new Error("Usage: node scripts/verified-kernels.mjs --write|--check|--artifact");
}
const mode = args[0];
if (mode === "--artifact") {
  const stored = JSON.parse(read(receipt));
  if (stored.version !== 1 || stored.bend !== version ||
      JSON.stringify(stored.inputs) !== JSON.stringify(inputs()) ||
      stored.javascript !== hash(read(output)) || stored.declarations !== hash(read(declarations))) {
    throw new Error("Verified kernel artifact is stale. Run bun run proof:generate with the pinned Bend compiler.");
  }
  console.log("Verified kernel artifact matches its proof sources and bridge.");
} else {
  const env = { ...process.env, BEND_NO_TELEMETRY: "1" };
  const bend = (...args) => execFileSync(process.env.BEND_BIN || "bend", args, {
    cwd: root, env, encoding: "utf8", maxBuffer: 16 * 1024 * 1024, timeout: 120_000,
  });
  if (bend("version").trim() !== `bend ${version}`) throw new Error(`Bend ${version} is required`);
  for (const path of sources.filter((path) => path.endsWith(".bend"))) {
    if (/@unsafe|\?\w|^\s*import\s+["']|^\s*import\s+0x/m.test(read(path))) {
      throw new Error(`Unsafe code, holes, foreign effects, and remote imports are forbidden in ${path}`);
    }
    for (const match of read(path).matchAll(/^import\s+(\S+)/gm)) {
      if (match[1] === "Base") continue;
      const imported = relative(root, resolve(root, dirname(path), match[1])).replaceAll("\\", "/");
      if (!sources.includes(imported) || !imported.endsWith(".bend")) {
        throw new Error(`Untracked proof dependency in ${path}: ${match[1]}`);
      }
    }
  }
  const checked = bend("PROOF.bend", "--check-only");
  if (!checked.includes("All terms check.")) throw new Error(`Bend did not confirm closed proofs: ${checked}`);
  const temp = mkdtempSync(join(tmpdir(), "fabric-bend-"));
  try {
    const emitted = join(temp, "kernel.js");
    bend("proofs/kernel.bend", "-o", emitted);
    const js = readFileSync(emitted, "utf8");
    const ast = ts.createSourceFile("kernel.js", js, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    const statements = [...ast.statements];
    const last = statements.slice(-2).map((statement) => statement.getText(ast).replace(/\s/g, ""));
    if (last[0] !== "cli(process.argv.slice(2));" || last[1] !== "io_exit($main$,null);") {
      throw new Error("Unrecognized Bend executable footer; review the compiler bridge before upgrading");
    }
    const defs = new Map(statements.filter(ts.isFunctionDeclaration).map((node) => [node.name?.text, node]));
    const abi = JSON.parse(read("proofs/abi.json"));
    const exports = Object.entries(abi).map(([name, signature]) => {
      const symbol = `$${name}$`;
      const arity = signature.length - 1;
      if (!/^[a-zA-Z][a-zA-Z0-9]*$/.test(name) || defs.get(symbol)?.parameters.length !== arity) {
        throw new Error(`Missing or incompatible compiled definition: ${name}`);
      }
      return `export const ${name} = /* @__PURE__ */ run_lib(${symbol}, ${arity});`;
    });
    // Only remove the two checked CLI invocations and expose actual compiler
    // definitions through Bend's own trampoline. No algorithm is translated.
    const library = js.slice(0, statements.at(-2).getFullStart()) + "\n" + exports.join("\n");
    const result = await build({
      stdin: { contents: library, sourcefile: "bend-kernel.js", resolveDir: root },
      bundle: true, write: false, format: "esm", platform: "node", packages: "external", target: "es2022",
      legalComments: "none", treeShaking: true,
      banner: { js: `// Generated by Bend ${version}; do not edit. See LAWS.bend and PROOF.bend.\n// Includes adapted Bend runtime/Base code, Copyright 2026 HigherOrderCO, Apache-2.0.\n// CLI removed and exports added by Pi Fabric; see THIRD_PARTY_NOTICES.md.` },
    });
    const generated = result.outputFiles[0].text;
    const generatedAst = ts.createSourceFile("generated.js", generated, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    if (generatedAst.statements.some((s) => ts.isImportDeclaration(s)) || /\b(?:process|globalThis|io_exit|io_push)\b/.test(generated)) {
      throw new Error("Effectful runtime escaped into the pure generated library");
    }
    const types = "// Generated ABI declarations; see proofs/abi.json.\n" + read("proofs/types.d.ts") + "\n" +
      Object.entries(abi).map(([name, signature]) => {
        const args = signature.slice(0, -1).map(([name, type]) => `${name}: ${type}`).join(", ");
        return `export declare function ${name}(${args}): ${signature.at(-1)};`;
      }).join("\n") + "\n";
    const manifest = JSON.stringify({ version: 1, bend: version, inputs: inputs(), javascript: hash(generated), declarations: hash(types) }, null, 2) + "\n";
    for (const [path, contents] of [[output, generated], [declarations, types], [receipt, manifest]]) {
      if (mode === "--write") {
        mkdirSync(resolve(root, "src/verified/generated"), { recursive: true });
        writeFileSync(resolve(root, path), contents);
      } else if (read(path) !== contents) {
        throw new Error(`${path} differs from freshly proved/generated output; run bun run proof:generate`);
      }
    }
    console.log(`Bend ${version}: all laws checked; ${Object.keys(abi).length} executable kernels ${mode === "--write" ? "generated" : "reproduced"} (${Buffer.byteLength(generated)} bytes).`);
  } finally {
    rmSync(temp, { recursive: true, force: true });
  }
}
